# Размер одного блока на игровом поле в пикселях
block_size = 17

# Ширина, высота игрового поля в блоках
board_width = 40
board_height = 40

# Имя игрока по умолчанию (для таблицы рекордов)
player_name = 'Hazadus'